services:
    doppy_routing.router:
        class: Symfony\Cmf\Component\Routing\ChainRouter
        arguments:
            - "@logger"
        tags:
          - { name: monolog.logger, channel: doppy_routing }
        calls:
            - [ setContext, [ "@router.request_context" ]]
